id: P010388
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 20:47:15.028710
source_metadata:
  id: bdr:W1CZ2262
  title: ལྷ་ས་གཙུག་ལག་ཁང་གི་གནས་བཤད་མདོར་བསྡུས
  author: ''
  volumes:
    c09fe6b103854b8fac05d62ffacdd13b:
      image_group_id: I1CZ2301
      title: ''
      volume_number: 1
      total_pages: 146
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
