id: P010388
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ2262
  title: ལྷ་ས་གཙུག་ལག་ཁང་གི་གནས་བཤད་མདོར་བསྡུས
  author: ''
  volumes:
    c09fe6b103854b8fac05d62ffacdd13b:
      image_group_id: I1CZ2301
      title: ''
      volume_number: 1
      total_pages: 146
      base_file: v001.txt
